apiVersion: v1
kind: Pod
metadata:
  name: static-storage-demo
spec:
  containers:
    - name: app
      image: nginx:1.27
      volumeMounts:
        - name: storage-vol
          mountPath: /data
  volumes:
    - name: storage-vol
      persistentVolumeClaim:
        claimName: static-pvc
