apiVersion: v1
kind: Service
metadata:
  name: monitored-service
  namespace: default
  labels:
    app: monitored-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: monitored-app
