aws_region         = "ap-south-1"
environment        = "production"
vpc_cidr           = "10.0.0.0/16"
public_subnet_cidr = "10.0.1.0/24"
availability_zone  = "ap-south-1a"
instance_type      = "t3.micro"
s3_bucket_name     = "sathwik-session19-cloud-terraform-demo-2026"
